DROP TABLE ORDER_DETAIL;
DROP TABLE ORDERS;
DROP TABLE MEMBER;
DROP TABLE PRODUCT;
DROP TABLE CART;

CREATE TABLE MEMBER(
    mID   VARCHAR2(20) PRIMARY KEY,
    mNAME VARCHAR2(50) NOT NULL,
    mADDR VARCHAR2(255),
    mTEL  VARCHAR2(30),
    mMAIL VARCHAR2(30) NOT NULL
);
SELECT * FROM MEMBER;


CREATE TABLE PRODUCT(
    pCODE  VARCHAR2(5) PRIMARY KEY,
    pNAME  VARCHAR2(50),
    PRICE  NUMBER(6) NOT NULL CHECK(PRICE>0),
    pSTOCK NUMBER(3) NOT NULL CHECK(pSTOCK>=0)   
);
SELECT * FROM PRODUCT;

DROP SEQUENCE CART_SEQ;
CREATE SEQUENCE CART_SEQ MAXVALUE 999999999 NOCACHE;
CREATE TABLE CART(
    cNO   NUMBER(9) PRIMARY KEY,
    mID   VARCHAR2(20) REFERENCES MEMBER(mID) NOT NULL,
    pCODE VARCHAR2(5) REFERENCES PRODUCT(pCODE) NOT NULL,
    QTY   NUMBER(3) CHECK(QTY>0) NOT NULL,
    COST  NUMBER(9) 
);
SELECT * FROM CART;

DROP SEQUENCE ORDERS_SEQ;
CREATE SEQUENCE ORDERS_SEQ MAXVALUE 999999999 NOCACHE;
CREATE TABLE ORDERS(
    oNO   VARCHAR2(9) PRIMARY KEY,
    mID   VARCHAR2(20) REFERENCES MEMBER(mID) NOT NULL,
    oNAME VARCHAR2(50) NOT NULL,
    oADDR VARCHAR2(255) NOT NULL,
    oTEL  VARCHAR2(30) NOT NULL,
    oDATE DATE DEFAULT SYSDATE
);
SELECT * FROM ORDERS;

DROP SEQUENCE ORDER_DETAIL_SEQ;
CREATE SEQUENCE ORDER_DETAIL_SEQ;
CREATE TABLE ORDER_DETAIL(
    odNO  NUMBER(9) PRIMARY KEY,
    oNO   VARCHAR2(9) REFERENCES ORDERS(oNO) NOT NULL,
    pCODE VARCHAR2(5) REFERENCES PRODUCT(pCODE) NOT NULL,
    QTY   NUMBER(3) CHECK(QTY>0) NOT NULL,
    COST  NUMBER(9)     
);
SELECT * FROM ORDER_DETAIL;

INSERT INTO MEMBER VALUES('abc', '홍길동', '서울 서대문구', '010-9999-9999', 'hong@hong.com');
INSERT INTO MEMBER VALUES('def', '김길동', '경기도 수원시', '010-8888-8888', 'kim@kim.com');
SELECT * FROM MEMBER;

INSERT INTO PRODUCT VALUES('A1', '맥주', 3000, 100);
INSERT INTO PRODUCT VALUES('B1', '땅콩', 3000, 100);
INSERT INTO PRODUCT VALUES('C1', '소독약',7000, 100);
INSERT INTO PRODUCT VALUES('A2', '마스크', 200, 100);
INSERT INTO PRODUCT VALUES('B2', '오징어', 5000, 100);
SELECT * FROM PRODUCT;

-- 주문번호 생성하기 연습('230728' || ' 001 => '2307280001')
SELECT TO_CHAR(SYSDATE, 'RRMMDD') || TRIM(TO_CHAR(ORDERS_SEQ.NEXTVAL, '000')) oNO FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'RRMMDD') || SUBSTR(TO_CHAR(ORDERS_SEQ.NEXTVAL, '000'), 2, 3) oNO FROM DUAL;

-- ■■■ 첫번째 홍길동님 주문서(23.07.26) ■■■
-- 1. 홍길동(abc)님 장바구니 물건 담기
INSERT INTO CART VALUES (CART_SEQ.NEXTVAL, 'abc', 'A1', 3, (SELECT PRICE FROM PRODUCT WHERE PCODE='A1')*3);
INSERT INTO CART VALUES (CART_SEQ.NEXTVAL, 'abc', 'B1', 1, (SELECT PRICE FROM PRODUCT WHERE PCODE='B1')*1);
SELECT * FROM CART;

-- 2. 홍길동(abc)님 주문하기
    -- 2-1. ORDERS(주문)테이블
    INSERT INTO ORDERS( ONO, MID, ONAME, OADDR, OTEL)
        VALUES(TO_CHAR(SYSDATE, 'RRMMDD') || TRIM(TO_CHAR(ORDERS_SEQ.NEXTVAL, '000')), 'abc', '홍길동', '서울 서대문구',
            '010-9999-9999');
    SELECT * FROM ORDERS;
    -- 2-2. ORDER_DETAIL(주문상세) 테이블(장바구니에 담은 물건을 한번에 주문할 경우)
        주문상세 테이블에 INSERT할 때 필요한 서브쿼리 연습
    SELECT 
      ORDER_DETAIL_SEQ.NEXTVAL odNO,
      TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.CURRVAL, '000')) ONO, PCODE, QTY, COST
    FROM CART WHERE MID='abc'; -- 주문상세 테이블에 insert할 때 필요한 서브쿼리
  DROP SEQUENCE ORDER_DETAIL_SEQ; -- 위에 연습했으니 시퀀스 새로 생성
  CREATE SEQUENCE ORDER_DETAIL_SEQ MAXVALUE 999999999 NOCYCLE NOCACHE;
  INSERT INTO ORDER_DETAIL (odNO, oNO, pCODE, QTY, COST)
    SELECT 
      ORDER_DETAIL_SEQ.NEXTVAL odNO,
      TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.CURRVAL, '000')) ONO,PCODE, QTY, COST
    FROM CART WHERE MID='abc';
  SELECT * FROM ORDER_DETAIL; -- ORDERS 테이블과 ORDER_DETAIL테이블 완성




